server {
    listen 443 ssl;
    server_name 91.135.163.91;
	
    root /var/www/html;

    #access_log /var/log/nginx/debug.log debug_log;

    # Server-Certificate
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # Client-Certt-Validation (mTLS)
    ssl_verify_client optional;
    ssl_verify_depth 2;
    ssl_client_certificate /etc/nginx/certs/ca.client.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;

    # Catch-all:
	location / {
	return 444;
    }

    # API: Cert required
    location /api/ {
      if ($ssl_client_verify != SUCCESS) { return 403; }
      proxy_pass http://localhost:7070/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # mTLS-Status
      proxy_set_header X-Client-Verify $ssl_client_verify;
      proxy_set_header X-Client-DN     $ssl_client_s_dn;
    }

     # clientcertios (for iOS)
    location /api/mqtt/v1/validate/clientcertios {
      proxy_pass http://localhost:7070/api/mqtt/v1/validate/clientcertios;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

     # mTLS-Status
      proxy_set_header X-Client-Verify $ssl_client_verify;
      proxy_set_header X-Client-DN     $ssl_client_s_dn;
     }

      # clientcertand (for Android)
    location /api/mqtt/v1/validate/clientcertand {
      proxy_pass http://localhost:7070/api/mqtt/v1/validate/clientcertand;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

     # mTLS-Status
      proxy_set_header X-Client-Verify $ssl_client_verify;
      proxy_set_header X-Client-DN     $ssl_client_s_dn;
     }

    # PC,Mac
    location /api/mqtt/v1/validate/clientcert {
      if ($ssl_client_verify != SUCCESS) { return 403; }
      proxy_pass http://localhost:7070/api/mqtt/v1/validate/clientcert;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

     # mTLS-Status
      proxy_set_header X-Client-Verify $ssl_client_verify;
      proxy_set_header X-Client-DN     $ssl_client_s_dn;
     }
     
}

