listener 8883
pid_file /run/mosquitto/mosquitto_8883.pid

certfile /etc/mosquitto/certs/cert.crt
keyfile  /etc/mosquitto/certs/cert.key
cafile   /etc/mosquitto/certs/bundle.crt
capath   /etc/mosquitto/client-ca.8883.d/

require_certificate true

persistence false

allow_anonymous false

password_file /etc/mosquitto/.passwd_8883

log_dest file /var/log/mosquitto/mosquitto_8883.log
